### ISSUE TITLE
Documentation has wrong Feedback and Pull requests links

### ISSUE THREAD

**Issue by hoornet** [Backendless/Flutter-SDK#1]
The links within "**Feedback** and **Pull Requests** are most welcome!" are wrong.

**Feedback** should point to: 
[https://github.com/Backendless/Flutter-SDK/issues](https://github.com/Backendless/Flutter-SDK/issues)
instead of 
[https://github.com/4lfant/Flutter-SDK/issues](https://github.com/4lfant/Flutter-SDK/issues)

**Pull requests** should point to:
[https://github.com/Backendless/Flutter-SDK/pulls](https://github.com/Backendless/Flutter-SDK/pulls)
instead of 
[https://github.com/4lfant/Flutter-SDK/pulls](https://github.com/4lfant/Flutter-SDK/pulls)

**Comment by 4lfant** [comment]
Hi @hoornet 
We've updated the links on Github. 
Thanks for help!
