### ISSUE TITLE
SignIn with social

### ISSUE THREAD

**Issue by lqmminh** [Backendless/Flutter-SDK#12]
I see breaking changes in 6.2.0 
"BREAKING Remove old social login methods: loginWithGoogle, loginWithFacebook & loginWithTwitter
BREAKING Remove deprecated geo service. You should use new spatial data types"
But don't see anything replace???

**Comment by msxenon** [comment]
any news about this issue ? i have the same problem with loginWithFacebook is Not defined

**Comment by lqmminh** [comment]
> any news about this issue ? i have the same problem with loginWithFacebook is Not defined

what is your version?
