### ISSUE TITLE
Mission (Serverless 101/2) runs fine with SDK ^0.1.1, fails with ^6.3.0

### ISSUE THREAD

**Issue by spacejunky** [Backendless/Flutter-SDK#13]
## To reproduce:

1/ Build & Run skeleton app (with additions to fulfillmission requirements) as dowloaded from CodelessShoppingCart
Observe that all is OK

2/ Update pubspec.yaml, replacing `backendless_sdk: ^0.1.1` with `backendless_sdk: ^6.3.0`

3/ Build & run again, *no other changes*.
Observe failure

> I/flutter (16776): BackendlessException: Wrong json format: Cannot deserialize instance of `java.util.HashMap<java.lang.Object,java.lang.Object>` out of START_ARRAY token
I/flutter (16776):  at [Source: UNKNOWN; line: -1, column: -1], code = null

At application level this occurs during the call to `addItem()`

## Flutter doctor output:

nigelhead@penguin:~/Projects/CodelessShoppingCartService$ flutter doctor -v
[✓] Flutter (Channel beta, 2.1.0-12.2.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 2.1.0-12.2.pre at /home/nigelhead/tools/flutter
    • Framework revision 5bedb7b1d5 (4 weeks ago), 2021-03-17 17:06:30 -0700
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/nigelhead/tools/androidsdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (Zulu 8.52.0.23-CA-linux64) (build
      1.8.0_282-b08)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 7.0.1-8+deb10u2 (tags/RELEASE_701/final)
    • cmake version 3.13.4
    • ninja version 1.8.2
    • pkg-config version 0.29

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for
      detailed instructions).

[✓] VS Code (version 1.55.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • nami (mobile)   • emulator-5554 • android-x64    • Android 9 (API 28)
    • Linux (desktop) • linux         • linux-x64      • Linux
    • Chrome (web)    • chrome        • web-javascript • Google Chrome 89.0.4389.72

! Doctor found issues in 1 category.

**Comment by lqmminh** [comment]
I think we leave backendless because they react so late :(

**Comment by lqmminh** [comment]
Not null safety, not upgrade Dependencies

**Comment by spacejunky** [comment]
Further info, after some manual bisecting ...

1.1.8 is the last functioning version,
6.0.0 is the first that fails

**Comment by holailusoria** [comment]
With all the problems that you face, it is better to write to support.backendless.com
