### ISSUE TITLE
Flutter SDK: login throws exception when compiled for web

### ISSUE THREAD

**Issue by aspernol** [Backendless/Flutter-SDK#14]
Hi,
I'm using Flutter 2.0.6 and backendless SDK 7.0.0-nullsafety.0
When calling `_user = await Backendless.userService.login(user, password);` I get an exception:
`Login failed: PlatformException(error, Expected a value of type 'Object', but got one of type 'Null', null, null)`

`user` and `password` is set correctly and not `null` when calling the method.

**Comment by aspernol** [comment]
Upgraded to Flutter 2.2.2 and backendless_sdk: ^7.0.0
Problem still exists. Any suggestions?

**Comment by holailusoria** [comment]
Try with newer version 7.1.8.
The problem was fixed in release 7.1.7
