### ISSUE TITLE
The plugins `backendless_sdk` use a deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by Evgentret** [Backendless/Flutter-SDK#15]
To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing them since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

All released and published apps are stopped 8 days ago.

**Comment by holailusoria** [comment]
Fixed in release 7.1.3
