### ISSUE TITLE
backendless_sdk/BackendlessSdkPlugin.h' file not found

### ISSUE THREAD

**Issue by TheAlphamerc** [Backendless/Flutter-SDK#2]
> backendless_sdk/BackendlessSdkPlugin.h' file not found

This error occured on running project in xcode.

**Steps to reporduce error**

1. Install Backendless plugin.

1. Write necessary code  as per documentation.

1. go to ios folder.

1. Open  Runner.xcodeproj in xcode by double click on it.

1. Go to Product > Run.

<img width="1680" alt="Screenshot 2019-11-12 at 10 06 32 AM" src="https://user-images.githubusercontent.com/37103237/68642468-41e22780-0534-11ea-9c4b-bda8891606f6.png">

**Comment by 4lfant** [comment]
Hi @TheAlphamerc 

Does this issue still persists?

**Comment by 4lfant** [comment]
Please try to run your Flutter application in the IDE that supports it, for example IntelliJ IDEA or Visual Studio Code. You can find the instructions about how to setup the editor here:
https://flutter.dev/docs/get-started/editor
