### ISSUE TITLE
Flutter Web support

### ISSUE THREAD

**Issue by SebastianEngel** [Backendless/Flutter-SDK#3]
We're currently building our admin dashboard with Flutter Web and so wanted to access our Backendless data with the Flutter SDK. Unfortunately it seems like that's currently not possible.

I also assumed that the SDK is pure Dart, but as I found out, the Flutter SDK is only a wrapper around the native SDKs (it uses platform channels), which also makes it unusable for Flutter Web.

Is support for Flutter Web planned? 
Currently the only way to access Backendless from Flutter Web is probably the plain REST API, right?

**Comment by 4lfant** [comment]
Hi @SebastianEngel 

Yes, Flutter SDK is a plugin package and use Android SDK and Swift SDK underneath.
We consider to add Web support to our Flutter SDK in the next few months. So stay tuned!)

**Comment by 4lfant** [comment]
Sorry for the delayed response.
I want to announce that we have added the Web support for our Flutter SDK. Please update to the latest version and follow [the instructions](https://github.com/Backendless/Flutter-SDK#enable-web-support).
@SebastianEngel  @trejdych @PsHohe
