### ISSUE TITLE
version 1.1.3 build issue

### ISSUE THREAD

**Issue by wolfljj** [Backendless/Flutter-SDK#4]
```
backendless_sdk-1.1.3/ios/Classes/CustomArgumentsCoding/BackendlessReader.swift:72:16: error: value of optional type 'BLPoint??' not
    unwrapped; did you mean to use 'try!' or chain with '?'?
            return try? BLPoint.fromWkt(wkt)
                   ^~~~
                   try!
backendless_sdk-1.1.3/ios/Classes/CustomArgumentsCoding/BackendlessReader.swift:79:16: error: value of optional type 'BLLineString??' not
    unwrapped; did you mean to use 'try!' or chain with '?'?
            return try? BLLineString.fromWkt(wkt)
                   ^~~~
                   try!
backendless_sdk-1.1.3/ios/Classes/CustomArgumentsCoding/BackendlessReader.swift:86:16: error: value of optional type 'BLPolygon??' not
    unwrapped; did you mean to use 'try!' or chain with '?'?
            return try? BLPolygon.fromWkt(wkt)
                   ^~~~
                   try!
```

**Comment by 4lfant** [comment]
Hi @wolfljj 

Can you please provide the steps/code sample to reproduce this issue?

**Comment by wolfljj** [comment]
no more steps.
just add backendless to pubspec.yaml then use the sample code on pub.flutter
backendless version 1.1.3

Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.6 18G1012)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.43.0)


 String applicationID = '';
            String androidApiKey = '';
            String iosApiKey = '';
            Backendless.initApp(applicationID, androidApiKey, iosApiKey);
            // create a Map object. This will become a record in a database table
            Map testObject = new Map();
           
            Channel channel=await Backendless.messaging.subscribe();
            channel.addMessageListener((String stringMessage){
              print(stringMessage);
            });
            // add a property to the object.
            // The property name ("foo") will become a column in the database table
            // The property value ("bar") will be stored as a value for the stored record
            testObject["foo"] = "bar";
            // Save the object in the database. The name of the database table is "TestTable".
            Backendless.data.of("TestTable").save(testObject).then((response) =>
                print(
                    "Object is saved in Backendless. Please check in the console."));

**Comment by 4lfant** [comment]
Don't you forget to specify your App ID and API keys, @wolfljj ?

**Comment by wolfljj** [comment]
no,I use my own app id and api keys when build,this is build error,you can see it,

**Comment by olgadanylova** [comment]
Hello @wolfljj,
I've checked your code and everything works fine.

Please check what version of Swift-SDK dependency do you have. Current version is 5.7.6 - please update is you have the older one.

If this issue is still present, please create a topic on our [support forum](https://support.backendless.com/) and attach a [sample project](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue, so we could check it.

**Comment by olgadanylova** [comment]
Issue is closed due to the lack of activity.
