### ISSUE TITLE
Flutter Offline Database Support

### ISSUE THREAD

**Issue by danisev7** [Backendless/Flutter-SDK#5]
Hi,

It will be very useful that Backendless Flutter SDK had offline database support. 

From my point of view, this is the only point where Firebase beats Backendless.

Regards,
Dani

**Comment by 4lfant** [comment]
Hi @danisev7 

I'm happy to inform you that we are currently working on an Offline functionality for the Flutter SDK. And we will release it in the immediate future.

**Comment by danisev7** [comment]
@4lfant  I'm so glad to hear this!!!

Immediate future means in the coming weeks? I have a finished an App but I'm pending to add offline database functionality. If Backendless Flutter SDK will add offline database support in next weeks I can wait, otherwise I will have to develop it.

**Comment by nunomazer** [comment]
Hi @4lfant any news about this feature ?

**Comment by 4lfant** [comment]
Hi @nunomazer 
The Offline Support functionality is mostly done. Currently we polish and improve it with new features like Json support etc. So stay tuned 😉

**Comment by bgervan** [comment]
Hi, any update for offline support?

**Comment by LoveriusB** [comment]
Hi there. Is this feature out yet? 

cheers
