### ISSUE TITLE
Getting current user.

### ISSUE THREAD

**Issue by i2pacg** [Backendless/Flutter-SDK#6]
Hello there ,
using Backendless-web
the following will always return null .
```
final currentUser = await Backendless.userService.currentUser();
print("currentUser $currentUser");
```

this works .
```
final userId = await Backendless.userService.loggedInUser();
print("Getting user $userId");
```

this will return 
_**PlatformException(error, NoSuchMethodError: tried to call a non-function, such as null: 'dart.global.Backendless.UserService.findById', null)**_

```
final currentUser =
await Backendless.userService.findById(loggedInUserId);
print("currentUser $currentUser");
```

Backendless helped me a lot the past few years and I've enjoyed learning through it very much.

**Comment by 4lfant** [comment]
Hi @i2pacg 

The `currentUser` approach works fine for me. Please make sure to login the user before calling `userService.currentUser()`:

```dart
var user = await Backendless.userService.login("email", "password");

var currentUser = await Backendless.userService.currentUser();
print("CurrentUser: $currentUser");
```

The method `Backendless.userService.findById` is not available for web. We will consider  to add the support for this method.
