### ISSUE TITLE
Invalid argument

### ISSUE THREAD

**Issue by david-all-win-software** [Backendless/Flutter-SDK#7]
I'm trying to run a custom service from the SDK, however I don't know how to send the arguments in the correct format
```
Backendless.customService
                      .invoke("onBoarding", "flutter", {"pageSize": 1}).then((data) {
                         print("backndless response: " + data.toString());
                     }).catchError((e) {
                         print(e);
                     });
```
The exception I get is:
`PlatformException(error, Invalid argument: Instance of 'NativeJavaScriptObject', null)`

Could you provide an example of the accepted format for sending arguments from the flutter SDK?

**Comment by david-all-win-software** [comment]
This issue is being followed up from: [](https://support.backendless.com/t/invalid-argument/11504/3)

**Comment by david-all-win-software** [comment]
I have found the solution, my problem was when sending an array as an argument, it must be sent in json (key / value) format, example: `Backendless.customService.invoke("onBoarding", "flutter",{"pageSize": 1, "param2": "parameter 2"}`

**Comment by david-all-win-software** [comment]
The original exception was caused in the backend when returning an object to the flutter SDK
![data object](https://user-images.githubusercontent.com/70285087/91477543-bbe16400-e85b-11ea-9cc5-2ff46b0bd299.png)
`PlatformException(error, Invalid argument: Instance of 'NativeJavaScriptObject', null)`

**Comment by 4lfant** [comment]
Solution from [support forum](https://support.backendless.com/t/invalid-argument/11504/14):
